version: "3.8"

services:
  api:
    image: "oven/bun"
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/main.ts'"
    # expose the right ports
    ports:
      - "3000:3000"
    # setup a host mounted volume to sync changes to the container
    volumes: 
      - "./server:/home/bun/app"
    environment:
      - ENV_VAL=${ENV_VAL}
